// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleWebApplication.Data;

#nullable disable

namespace SampleWebApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleWebApplication.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CompanyId");

                    b.ToTable("companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Name = "Tech Innovators Inc."
                        },
                        new
                        {
                            CompanyId = 2,
                            Name = "Global Solutions Ltd."
                        },
                        new
                        {
                            CompanyId = 3,
                            Name = "NextGen Technologies"
                        },
                        new
                        {
                            CompanyId = 4,
                            Name = "Enterprise Hub"
                        },
                        new
                        {
                            CompanyId = 5,
                            Name = "Creative Minds Corp."
                        },
                        new
                        {
                            CompanyId = 6,
                            Name = "Future Vision Inc."
                        },
                        new
                        {
                            CompanyId = 7,
                            Name = "Innovative Solutions"
                        },
                        new
                        {
                            CompanyId = 8,
                            Name = "Dynamic Enterprises"
                        },
                        new
                        {
                            CompanyId = 9,
                            Name = "Advanced Systems"
                        },
                        new
                        {
                            CompanyId = 10,
                            Name = "Smart Tech Solutions"
                        },
                        new
                        {
                            CompanyId = 11,
                            Name = "Premier Technologies"
                        },
                        new
                        {
                            CompanyId = 12,
                            Name = "Ultimate Innovations"
                        },
                        new
                        {
                            CompanyId = 13,
                            Name = "Pioneering Systems"
                        },
                        new
                        {
                            CompanyId = 14,
                            Name = "Creative Solutions"
                        },
                        new
                        {
                            CompanyId = 15,
                            Name = "Tech Pioneers"
                        },
                        new
                        {
                            CompanyId = 16,
                            Name = "Innovative Minds"
                        },
                        new
                        {
                            CompanyId = 17,
                            Name = "Global Tech Innovators"
                        },
                        new
                        {
                            CompanyId = 18,
                            Name = "NextGen Enterprises"
                        },
                        new
                        {
                            CompanyId = 19,
                            Name = "Enterprise Innovators"
                        },
                        new
                        {
                            CompanyId = 20,
                            Name = "Creative Tech Solutions"
                        });
                });

            modelBuilder.Entity("SampleWebApplication.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("DepartmentId");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 5,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentId = 6,
                            Name = "Operations"
                        },
                        new
                        {
                            DepartmentId = 7,
                            Name = "Customer Support"
                        },
                        new
                        {
                            DepartmentId = 8,
                            Name = "R&D"
                        },
                        new
                        {
                            DepartmentId = 9,
                            Name = "Logistics"
                        },
                        new
                        {
                            DepartmentId = 10,
                            Name = "Procurement"
                        },
                        new
                        {
                            DepartmentId = 11,
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            DepartmentId = 12,
                            Name = "Legal"
                        },
                        new
                        {
                            DepartmentId = 13,
                            Name = "Compliance"
                        },
                        new
                        {
                            DepartmentId = 14,
                            Name = "Strategy"
                        },
                        new
                        {
                            DepartmentId = 15,
                            Name = "Product Management"
                        },
                        new
                        {
                            DepartmentId = 16,
                            Name = "Engineering"
                        },
                        new
                        {
                            DepartmentId = 17,
                            Name = "Design"
                        },
                        new
                        {
                            DepartmentId = 18,
                            Name = "Administration"
                        },
                        new
                        {
                            DepartmentId = 19,
                            Name = "Security"
                        },
                        new
                        {
                            DepartmentId = 20,
                            Name = "Training"
                        });
                });

            modelBuilder.Entity("SampleWebApplication.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.HasKey("EmployeeId");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CompanyId = 1,
                            DepartmentId = 1,
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "田中 太郎",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            CompanyId = 2,
                            DepartmentId = 2,
                            HireDate = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "佐藤 花子",
                            Salary = 58000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            CompanyId = 3,
                            DepartmentId = 3,
                            HireDate = new DateTime(2018, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "鈴木 一郎",
                            Salary = 61000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            CompanyId = 4,
                            DepartmentId = 4,
                            HireDate = new DateTime(2021, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "高橋 由美",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            CompanyId = 5,
                            DepartmentId = 5,
                            HireDate = new DateTime(2017, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "井上 勝",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            CompanyId = 6,
                            DepartmentId = 6,
                            HireDate = new DateTime(2016, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "山本 久美",
                            Salary = 63000m
                        },
                        new
                        {
                            EmployeeId = 7,
                            CompanyId = 7,
                            DepartmentId = 7,
                            HireDate = new DateTime(2015, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "小林 健",
                            Salary = 59000m
                        },
                        new
                        {
                            EmployeeId = 8,
                            CompanyId = 8,
                            DepartmentId = 8,
                            HireDate = new DateTime(2020, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "加藤 愛",
                            Salary = 64000m
                        },
                        new
                        {
                            EmployeeId = 9,
                            CompanyId = 9,
                            DepartmentId = 9,
                            HireDate = new DateTime(2019, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "森田 進",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 10,
                            CompanyId = 10,
                            DepartmentId = 10,
                            HireDate = new DateTime(2021, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "山田 裕子",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 11,
                            CompanyId = 11,
                            DepartmentId = 11,
                            HireDate = new DateTime(2018, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "清水 真",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 12,
                            CompanyId = 12,
                            DepartmentId = 12,
                            HireDate = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "斎藤 明",
                            Salary = 63000m
                        },
                        new
                        {
                            EmployeeId = 13,
                            CompanyId = 13,
                            DepartmentId = 13,
                            HireDate = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "田村 茂",
                            Salary = 59000m
                        },
                        new
                        {
                            EmployeeId = 14,
                            CompanyId = 14,
                            DepartmentId = 14,
                            HireDate = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "中村 和子",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 15,
                            CompanyId = 15,
                            DepartmentId = 15,
                            HireDate = new DateTime(2016, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "渡辺 幸",
                            Salary = 64000m
                        },
                        new
                        {
                            EmployeeId = 16,
                            CompanyId = 16,
                            DepartmentId = 16,
                            HireDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "西田 修",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 17,
                            CompanyId = 17,
                            DepartmentId = 17,
                            HireDate = new DateTime(2018, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "松本 智子",
                            Salary = 63000m
                        },
                        new
                        {
                            EmployeeId = 18,
                            CompanyId = 18,
                            DepartmentId = 18,
                            HireDate = new DateTime(2017, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "福田 実",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 19,
                            CompanyId = 19,
                            DepartmentId = 19,
                            HireDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "藤田 清",
                            Salary = 64000m
                        },
                        new
                        {
                            EmployeeId = 20,
                            CompanyId = 20,
                            DepartmentId = 20,
                            HireDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "石田 優",
                            Salary = 65000m
                        });
                });

            modelBuilder.Entity("SampleWebApplication.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("product_price");

                    b.HasKey("ProductId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Smartphone",
                            Price = 799.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Tablet",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Monitor",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Keyboard",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Printer",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Scanner",
                            Price = 89.99m
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Speaker",
                            Price = 69.99m
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "Headphone",
                            Price = 39.99m
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Webcam",
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Router",
                            Price = 99.99m
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Hard Drive",
                            Price = 89.99m
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "USB Flash Drive",
                            Price = 19.99m
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "External SSD",
                            Price = 129.99m
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Power Bank",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Charger",
                            Price = 25.99m
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Projector",
                            Price = 299.99m
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "VR Headset",
                            Price = 399.99m
                        },
                        new
                        {
                            ProductId = 20,
                            Name = "Smartwatch",
                            Price = 199.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
